### ISSUE TITLE
GloDroid on RPi CM4

### ISSUE THREAD

**Issue by NumberOneGit** [GloDroid/glodroid_device#31] opened 2022-02-23 21:13 UTC
I'd like to test out GloDroid on the Raspbery Pi CM4.  The installer for Pi 4B only comes with an installer for SD cards but not the eMMC related files.  Is this something that I can take from another device or are there contents that are hardware specific?

**Comment by NumberOneGit** [comment] 2022-02-27 19:21
I am going to post this in the manifest repo.  Unfortunately, I am unable to delete the duplicate post here

**Comment by rsglobal** [comment] 2022-04-20 08:52
Duplicate of https://github.com/GloDroid/glodroid_manifest/issues/186

**Closed as completed by rsglobal** 2022-04-20 08:52 UTC
